#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
services:

  xpanse-db:
    container_name: xpanse-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=xpanse
      - MYSQL_USER=xpanse
      - MYSQL_PASSWORD=xpanse
      - MYSQL_ROOT_PASSWORD=xpanse
    ports:
      - "3306:3306"
    networks:
      - 'xpanse-local'

  terraform-boot:
    container_name: terraform-boot
    image: ghcr.io/eclipse-xpanse/terraform-boot:latest
    pull_policy: always
    ports:
      - '9090:9090'
    networks:
      - 'xpanse-local'

  policy-man:
    container_name: policy-man
    pull_policy: always
    image: ghcr.io/eclipse-xpanse/policy-man:latest
    command: --host=0.0.0.0
    ports:
      - '8090:8090'
    networks:
      - 'xpanse-local'

  tofu-maker:
    container_name: tofu-maker
    pull_policy: always
    image: ghcr.io/eclipse-xpanse/tofu-maker:latest
    ports:
      - '9092:9092'
    networks:
      - 'xpanse-local'

  zitadel:
    restart: 'always'
    container_name: 'zitadel'
    networks:
      - 'xpanse-local'
    image: ghcr.io/eclipse-xpanse/xpanse-zitadel-dev-server:latest # image built locally by commiting an already initialized zitadel server
    command: 'start --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8088:8080'

  db:
    container_name: 'zitadel-db'
    restart: 'always'
    image: ghcr.io/eclipse-xpanse/xpanse-zitadel-dev-db:latest # image built locally by commiting an already initialized zitadel Postgres DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres" ]
      interval: '10s'
      timeout: '2400s'
      retries: 500
      start_period: '20s'
    networks:
      - 'xpanse-local'

networks:
  xpanse-local: